[workspace]
resolver = "3"
members = [
  "crates/*",
  "py-stk",
]
default-members = [
  "crates/*",
]

[workspace.package]
version = "0.1.0"
authors = [
  "Lukas Turcani <lukasturcani93@gmail.com>",
]
edition = "2024"
license = "MIT"
repository = "https://github.com/lukasturcani/stk"

[workspace.dependencies]
regex = "1.0"
stk-molecular-graph = { version = "0.1.0", path = "crates/stk-molecular-graph" }
