[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"

[project]
name = "stk"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
python-source = "python"
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "furo>=2024.8.6",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "pytest-benchmark>=4.0.0",
    "pytest-clarity>=1.0.1",
    "rdkit>=2025.3.6",
    "ruff>=0.12.12",
    "sphinx>=7.1.2",
    "sphinx-copybutton>=0.5.2",
]
